### ISSUE TITLE
Encodings do not check iterator limits

### ISSUE THREAD

**Issue by dascandy** [copperspice/cs_string#2]
This seems implicitly to violate the boundaries of the data structure you're iterating over, which would lead to invalid inputs causing crashes. For example, seeking 3 characters forward in a 3-code unit / 1 code point string would exceed the string length & read undefined memory.

**Comment by agserm** [comment]
Hi Peter,
I'm not sure I understand your comment fully here. It sounds like you are suggesting some code like this:

    CsString8 tmp = "<3 byte unicode char>";
    auto it = tmp.begin() + 3;
    someFunc(*it);

What would you expect this to do if not crash? I suppose it might be nice to have a checked iterator mode, where this would result in an exception instead of a crash but this code is certainly broken and has undefined behavior.

**Comment by dascandy** [comment]
The idea is to have an invalid UTF8 encoding (or in whatever encoding it is). The encoding does not get enough information to avoid going out of the invalid input, and there's no way to validate the input with a given encoding before parsing it.

**Comment by agserm** [comment]
The intent of CsString is to present a sequence of code points, invalid UTF-8 is not permitted so this issue does not arise.
