### ISSUE TITLE
size_t and int usage and other issue

### ISSUE THREAD

**Issue by ThomasKrenn** [copperspice/cs_string#4]
CsString has some inconsistent use of int and size_t. E.g. here:
int walk(int len, std::vector<storage_unit>::const_iterator iter)

What is the idea behind using the namespace CsString?
Does the statement 
`using namespace CsString;`
not lead to name conflicts with the class?

CsChar is not exported on Windows.
`class CsChar { ... };`
in file cs_char.h

Does the statement below create a temp. CsString?
`CsString::CsStringView text{ "hello" };`
If yes then any further use of 'text' will cause problems. 

Cmake 
Visual Studio C++ does not have the option -wl

The header files are not included in the project, but
this is helpful for IDEs that support header files in 
the project (e.g. CLion, Visual Studio).

Best regards 
Thomas Krenn

**Comment by agserm** [comment]
Thanks for your report. It looks like you have 4 different items and 2 questions. Can you submit these 4 items as four individual issues? Ideally, these would be four separate pull requests which we would be very happy to review.

As for the two questions:

1) The namespace CsString was used since we embed CsString in CopperSpice and we wanted a clear distinction. Since we never use and do not recommend `using namespace CsString` this has not been an issue. If you really need to add a using declaration, you will need to refer to this class as `CsString_utf8` rather than simply `CsString`

2) We will look into your question about the temporary CsString. This may be a valid concern and we will investigate.

Thanks again for your message and we look forward to working with you to resolve the other 4 items.

**Comment by ThomasKrenn** [comment]
I have split up the issues
