### ISSUE TITLE
MSVC linker warning:

### ISSUE THREAD

**Issue by ThomasKrenn** [copperspice/cs_string#7]
LINK : warning LNK4044: unrecognized option '/Wl,--no-undefined'; ignored

In cmake the compiler ID is the most robust way to identify the compiler used.
E.g. 
<$<CXX_COMPILER_ID:MSVC>:/wd4715>

**Comment by agserm** [comment]
We believe this warning is now resolved in 82bdfd0. Can you confirm and close the issue if this is the case? Thanks!

**Comment by ThomasKrenn** [comment]
Yes it is "solved", but setting on Windows the MSVC warning level to W1 is like telling the customer we don't support Windows.

The code below is are not necessary. Any decent CPP code compiles with /W3, which is the default warning level for MSVC.

`
  string (REGEX REPLACE "/W3" "" CMAKE_C_FLAGS   "${CMAKE_C_FLAGS}"  )
  string (REGEX REPLACE "/W3" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
`

**Comment by agserm** [comment]
Following up because we realized there may have a misunderstanding. There are two different changes in 82bdfd0. One of them ensures that the `-Wl,--no-undefined` flag is only passed to GCC as reported in this ticket.

The second change strips out a redundant `/W3` which is added unconditionally by CMake. This does not actually disable warnings, it simply works around a CMake bug in the MSVC generator. Without this code, CMake ends up passing `/W3 /W4` which produces an extraneous warning D9025.

**Comment by ThomasKrenn** [comment]
Hello Ansel,
thanks for your feedback.

> This does not actually disable warnings, ...

The code added sets the warning level to /W1. The recommended default is /W3.
Maybe this is a bug in the "ninja generators".

The "Visual Studio Generators" set warning level 3. 
A plain vanilla cmake .vcxproj file has in the "ClCompile" section:

    <WarningLevel>Level3</WarningLevel>

(This above line is missing in the copperspice generated .vcxproj files.)


> Without this code, CMake ends up passing /W3 /W4

To set /W4 some extra code is necessary. There is a good discussion on stackoverflow:
https://stackoverflow.com/questions/2368811/how-to-set-warning-level-in-cmake

To set /W4 with newer CMake versions:

    if (MSVC)
        # warning level 4
        add_compile_options(/W4)
    else()
        # lots of warnings and all warnings as errors
        add_compile_options(-Wall -Wextra -pedantic -Werror)
    endif()
